### ISSUE TITLE
Rows in the travelers table that are actually multiple travelers

### ISSUE THREAD

**Issue by fechan** [eba-diary/Travelogues-db-conversion#6]
The following rows in the travelers table are actually a conglomerate list of two or more travelers (except id 209 "International Engraving..."):
![image](https://user-images.githubusercontent.com/56131910/94885477-1d7d8b00-0425-11eb-8f78-b291446b26e6.png)

**ID 209 is not an error. The publisher appears as an author in Kalfatovik! This is because it is a photo album whose photographers are apparently unknown.**

Whoever is splitting these travelers into multiple travelers should also make sure to add them as a contributor to whatever publication they were a contributor to by adding an entry to the `contributions` table with the new traveler's ID and the ID of the publication they contributed to.

If you execute the following SQL, it will show a list of publications that each conglomeration listed above has contributed to, including the `publication_id` necessary to fill create a contribution in the `contributions` table. Refer to the diagram [here](https://github.com/eba-diary/Travelogues-db-conversion/issues/2#issuecomment-687500882) to see how contributions relates to the other tables.
```sql
select t.id, traveler_id, t.name, p.id publication_id, p.title from contributions c
	inner join publications p on c.publication_id = p.id
	inner join travelers t on c.traveler_id = t.id
	where traveler_id in (7,65,146,206,254,304)
```

**Comment by ketchley** [comment]
Updated these travelers in the database.  Note that traveler 146 Margot Asquith, Countess of Oxford and Asquith is a single individual.
